### ISSUE TITLE
Use Refresh Tokens Option Not Working (No Error Displayed)

### ISSUE THREAD

**Issue by tylersand** [tjoudeh/AngularJSAuthentication#32]
I am trying to test the User Refresh Tokens option, both in the sample hosted application and locally on my machine, but both just display the red error box without an error message upon clicking Login.  Is there something that I am missing or is this broken?  Thanks!

![image](https://cloud.githubusercontent.com/assets/16942321/22177663/5853875a-dff0-11e6-9655-d328ff5381fc.png)

**Comment by tjoudeh** [comment]
Hello @tylersand I've tried to login from my and its working as expected as the image below, can you try creating a new user and see if this will work for you?

![image](https://cloud.githubusercontent.com/assets/3114431/22181753/2394c9b0-e09b-11e6-9d91-145020b50827.png)

**Comment by tylersand** [comment]
Thanks for the quick reply.  I tested a new account and it worked as expected.  The credentials that were not working were:

Username:  Taiseer
Password:  SuperPass

Is that particular about that account why it would not work?  Thanks again!

**Comment by diegogodinho** [comment]
I had the same problem, I'm using my local database and Web Api locally as well.

I've tried to create a new user and still the same problem.

Any suggestion?

**Comment by diegogodinho** [comment]
it happened because I've put the wrong 'AllowedOrigin' into client table, it was with a incorrect slash at end of that string, and I didn't notice that i was receiving this message :
'XMLHttpRequest cannot load http://localhost:26264/token. The 'Access-Control-Allow-Origin' header has a value 'http://localhost:32150/' that is not equal to the supplied origin. Origin 'http://localhost:32150' is therefore not allowed access.'
